export enum SocketCommand {
    StartTime = 'startTime',
    StopTime = 'stopTime',
    CorrectAnswer = 'correctAnswer',
    NextQuestion = 'nextQuestion',
    SetCurrentQuestion = 'setCurrentQuestion',
    ShowAllAnswers = 'showAllAnswers',
    NextImage = 'nextImage',
    SetView = 'setView',
    NextRound = 'nextRound',
    NextStartingPlayer = 'nextStartingPlayer',
    NextPlayerToComplete = 'nextPlayerToComplete',
    SetPlayerName = 'setPlayerName',
    SetPlayerTime = 'setPlayerTime',
    SetPlayerCameraLink = 'setPlayerCameraLink',
}
